# Generated by Django 5.2.8 on 2025-11-23 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_campaign_remove_project_category_and_more'),
        ('votes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'project_campaign')},
        ),
        migrations.AddField(
            model_name='vote',
            name='project_campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='projects.projectcampaign'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('is_overall', True)), fields=('voter', 'project_campaign'), name='one_overall_vote_per_entry'),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='project',
        ),
    ]
