# Generated by Django 5.2.8 on 2025-11-23 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_alter_vote_options_alter_vote_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='one_overall_vote_per_entry',
        ),
    ]
