# Generated by Django 5.2.8 on 2025-11-23 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('projects', '0003_alter_project_options_rename_title_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/project-images/'),
        ),
    ]
