# Generated by Django 5.2.8 on 2025-11-23 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_options_campaign_categories_and_more'),
        ('categories', '0001_initial'),
        ('projects', '0004_project_campaign_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.CreateModel(
            name='ProjectCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('category', models.ForeignKey(blank=True, help_text='Category for this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Project Campaign Entries',
                'unique_together': {('project', 'campaign')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='campaigns',
            field=models.ManyToManyField(related_name='participating_projects', through='projects.ProjectCampaign', to='campaigns.campaign'),
        ),
    ]
