# Generated by Django 5.2.8 on 2025-11-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='campaigns', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='flyers/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Publish campaign'),
        ),
    ]
