# Generated by Django 5.2.8 on 2025-11-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_options_campaign_categories_and_more'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='categories',
            field=models.ManyToManyField(related_name='campaigns', to='categories.category'),
        ),
    ]
